twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    exception_controller: null
    form_themes: ['form/mosparo_form.html.twig']

    globals:
        mosparoName: '%env(mosparo_name)%'
        defaultColorMode: '%env(default_color_mode)%'

when@test:
    twig:
        strict_variables: true
