services:
  db:
    # We recommend the mariadb image
    image: mariadb:10.6.4-focal
    # If you want to use MySQL, uncomment the following line (and comment the one above)
    #image: mysql:8.0.27
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=mosparo_root_pw
      - MYSQL_DATABASE=mosparo
      - MYSQL_USER=mosparo
      - MYSQL_PASSWORD=mosparo_password
    expose:
      - 3306
      - 33060
  mosparo_web:
    image: mosparo/mosparo:v0.3.1
    ports:
      - 8080:80
    restart: always
    environment:
      - MOSPARO_ENABLE_WEBSERVER=1
      # If you want to run the cron jobs in a seperated container, uncomment the following lines
      #- MOSPARO_ENABLE_CRON=0
    volumes:
      - mosparo_data:/mosparo-data
  # If you want to run the cron jobs in a seperated container, uncomment the following lines
  #mosparo_cron:
  #  image: mosparo/mosparo:v0.3.1
  #  restart: always
  #  environment:
  #    - MOSPARO_ENABLE_WEBSERVER=0
  #  volumes:
  #    - mosparo_data:/mosparo-data
volumes:
  db_data:
  mosparo_data: